# Introduction à Python

Ici vous trouverez des exercices relativement simples qui permettent une (re)prise en main de Python.

# 1. Définition de fonctions

Définissez 5 fonctions :

1. <code>sum_of_three</code> : renvoie le somme de trois nombres donnés en argument. Exemple: sum_of_three(1,1,1) => 3


2. <code>cube_volume</code> : renvoie le volume d'un cube de coté n. Exemple: cube_volume(2) => 8.


3. <code>is_pair</code> : renvoie <code>True</code> si le nombre donné en argument est un nombre pair. Exemple is_pair(156) => True.


4. <code>belongs_to</code> : renvoie <code>True</code> si une chaine de caractère donnée contient un mot donné. Exemple: belongs_to("Il fait beau", "beau") => True


5. <code>is_a_question</code> : renvoie <code>True</code> si un string finit par "?". Exemple : is_a_question("Comment t'appelles tu ?") => True

In [2]:
def sum_of_three(a: int, b:int, c: int) -> int:
    return a + b + c

def cube_volume(side: int) -> int:
    return side ** 3

def is_pair(num: int) -> bool:
    return num % 2 == 0

def belongs_to(sentence: str, word: str) -> bool:
    return word in sentence

def is_a_question(sentence: str) -> bool:
    return sentence.endswith("?")

In [4]:
assert sum_of_three(1, 2, 3) == 6

In [5]:
assert cube_volume(side=3) == 27

In [6]:
assert is_pair(2222)

In [7]:
assert belongs_to("hello world!", "hello")

In [8]:
assert is_a_question("Hello world ?")

# 2. Problèmes divers

1. J'ai organisé une soirée piscine en l'absence de mes parents. Je suis sur le point d'aller me coucher et j'aimerais savoir à quelle heure je dois me lever pour faire le ménage. Je sais qu'ils doivent rentrer demain, qu'ils partent à 9h et qu'ils sont à 300km de la maison. Avant quelle heure dois-je avoir fait le ménage demain ? Définissez une fonction qui permette d'estimer l'heure d'arrivée en fonction d'un paramètre v, la vitesse moyenne de la voiture de mes parents sur la route.


2. On appelle diviseur propre de n, tout entier naturel qui divise exactement n, n exclu. On appelle nombre premier tout entier naturel supérieur à 1 qui possède exactement deux diviseurs propres, lui-même et l'unité. Un entier naturel est dit parfait s'il est égal à la somme de tous ses diviseurs propres. Écrire trois fonctions : somDiv, estParfait, estPremier, telles que :

- <code>somDiv</code> retourne la somme des diviseurs propres d'un entier n (donné en paramètre).
- <code>estPremier</code> retourne <code>True</code> si n est un entier premier.
- <code>estParfait</code> retourne <code>True</code> si n est un entier parfait.

In [15]:
from datetime import datetime, timedelta

def arrival_time(average_speed: float) -> datetime:
    """ Average speed in km/h """
    start_time = datetime.today().replace(hour=9, minute=0, second=0, microsecond=0)
    time_taken = 300 / average_speed
    return start_time + timedelta(hours=time_taken)

arrival_time(100)

datetime.datetime(2024, 6, 25, 12, 0)

In [21]:
def somDiv(n: int) -> int:
    return sum(diviseur for diviseur in range(1, n) if n % diviseur == 0)

In [45]:
print(somDiv(7))

1


In [30]:
def estPremier(n: int) -> int:
    return somDiv(n) == 1

In [46]:
print(estPremier(6))
print(estPremier(7))
print(estPremier(8))
print(estPremier(11))

False
True
False
True


In [38]:
# def diviseurs(n: int):
#     for d in range(n):
#         if n % d == 0:
#             yield d

def estParfait(n: int) -> bool:
    return somDiv(n) == n

In [40]:
print(estParfait(6))

True


# 3. Numpy

L'objectif, ici, est de faire un petit rappel sur Numpy, de manipuler des tableaux multidimensionnels et d'appliquer certaines opérations d'algèbre linéaire sans utiliser de boucles <code>for</code>. Si vous bloquez, n'hésitez pas à parcourir le site de [numpy](https://numpy.org/) ou internet dans son ensemble.

In [23]:
import numpy as np # Faites tourner cette cellule

---

**Q1** - Créez un vecteur nul (vecteur rempli de 0) de longueur 5. 

Il doit ressembler à ceci:

```
array([0., 0., 0., 0., 0.])
```

---

**Q2** - Créez un vecteur contenant les valeurs entre 20 et 25.

Il doit ressembler à ceci:

```
array([ 20,  21,  22,  23,  24, 25])
```

---
**Q3** - Créez un vecteur de 10 élèments à intervalles réguliers entre `-5` et `5`.

Il doit ressembler à ceci:

```
array([-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ])
```

---

**Q4** - Créez la matrice suivante `A` comme un `ndarray` NumPy:

$
A = 
\begin{pmatrix}
5 & 6 & 12\\
5 & 9 & 0
\end{pmatrix}
$

---
**Q5** - Créez la matrice suivante `B` sans utiliser `np.array()` :

$
B = 
\begin{pmatrix}
1 & 1\\
1 & 1
\end{pmatrix}
$

---

**Q6** - Créez une matrice identité `C` de dimensions 3x3:

$
C = 
\begin{pmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{pmatrix}
$

---

**Q7** - Calculez la somme des deux matrices `A` et `D` et intégrez le résultats dans une matrice `mat_sum`:

$
A = 
\begin{pmatrix}
0 & 4\\
-2 & 1\\
-3 & 1
\end{pmatrix}
$

$
D =
\begin{pmatrix}
0 & -1\\
-1 & 4\\
2 & 3
\end{pmatrix}
$

# 5. Pandas et Matplotlib

L'objectif, ici, est de faire un rappel sur l'utilisation de Pandas et de Matplotlib.

Pour cela nous allons analyser le jeu de données ["Avocado Prices"](https://www.kaggle.com/datasets/neuromusic/avocado-prices) de Janvier 2015 à Mars 2018. Ce jeu de données est issu de la plateforme [Kaggle](https://www.kaggle.com/).

In [87]:
# Import des librairies
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

---
**Q1** - Chargez les données se trouvant dans le dossier data:

---
**Q2** - Affichez les 5 premières lignes du DataFrame créé :

---
**Q3** - Que remarquez vous ?

---
**Q4** - Supprimez la colonne <code>Unnamed</code> :

---
**Q5** - Affichez les dimensions du DataFrame :

---
**Q4** - Affichez le nom des colonnes :

---
**Q5** - Affichez le type des trois premières colonnes :

---
**Q6** - Regardez le type de la colonne <code>Date</code>, que remarquez vous ? A l'aide de la fonction <code>pd.to_datetime</code> convertissez cette colone en <code>datetime</code> :

---

**Q7** - Pourquoi avoir procédé à cette opération ?


---

**Q8** - Nous allons répondre à notre première question de Data Scientist : Quelle quantité d'avocats est produite chaque année par chaque région du monde ?

Pour répondre à cette question, nous devons agréger les lignes en fonction de l'année de la colonne <code>region</code> et de la colonne <code>Date</code>. Pour cela utilisez les fonctions <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html"><code>DataFrame.groupby()</code></a> et <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sum.html"><code>DataFrame.sum()</code></a>.


---

**Q9** - Maintenant que nous avons ce DataFrame aggrégé, il est temps de représenter graphiquement (barplot) la production de l'Albany pour chaque année. Pour cela utilisez la fonction <a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.plot.html"><code>DataFrame.plot()</code></a> et la méthode <code>DataFrame.loc</code>.

---

**Q10** - Considérons que l'année 2018 de production d'avocats de l'Albanie ne soit pas complète. Représentez une nouvelle fois cette production par année sans l'année 2018.

---

**Q11** - Interessons nous maintenant à l'évolution du prix moyen des avocats biologiques. Représentez grapghiquement le prix de ceux ci au cours du temps.